[package]
name = "tr-lang"
version = "0.1.3"
edition = "2018"
authors = ["Kerem Göksu <superkerem13@gmail.com>"]
licence = "MIT"
description = "A programming language made to bring syntax closer to Turkish"
homepage = "https://github.com/kaiserthe13th/tr-lang"
documentation = "https://github.com/kaiserthe13th/tr-lang/wiki"
readme = "README.md"
repository = "https://github.com/kaiserthe13th/tr-lang"
keywords = ["programming-language", "lexer", "parser", "bytecode"]
categories = ["compilers"]
exclude = [
    "tests/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
